<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Module01" Id="{fd23d038-0b57-09ef-1955-d94c8e0517ac}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Module01 EXTENDS FB_Module
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[// https://peterzerlauth.com/
SUPER^();]]></ST>
    </Implementation>
    <Method Name="M_Running" Id="{2098ebcf-6139-0c40-232a-a4f51cd3a4e0}">
      <Declaration><![CDATA[METHOD PROTECTED M_Running
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Starting" Id="{a5672791-5f37-476b-802a-3f59e5531bf4}">
      <Declaration><![CDATA[METHOD PROTECTED M_Starting : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[M_Starting:= SUPER^.M_Starting();]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_Stopping" Id="{8deb5179-ef4f-4df8-bb39-ce953d8989f1}">
      <Declaration><![CDATA[METHOD PROTECTED M_Stopping : BOOL // Return state complete
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[// State Stopping
M_Stopping:= SUPER^.M_Stopping();]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>